;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        electric-newline-and-maybe-indent
        emmet-expand-line
        indent-for-tab-command
        iy-go-to-char--command
        mouse-set-region
        my/beginning-of-line
        my/open-line
        org-self-insert-command
        simpleclip-cut
        undo-fu-only-undo
        ))

(setq mc/cmds-to-run-once
      '(
        comint-interrupt-subjob
        keyboard-quit
        mark-whole-buffer
        shell
        simpleclip-copy
        simpleclip-paste
        ))
